// shared/user_config.ts
import type { SystemTimeTimezone, UserConfig } from './types';
import { DEFAULT_USER_CONFIG } from './constants';

const STORAGE_KEY = 'user_config';

// ============================================================
// IANA timezone → fixed UTC offset migration (P0.34)
// ============================================================
const IANA_TO_OFFSET: Record<string, string> = {
    'Africa/Abidjan': 'UTC',
    'Africa/Accra': 'UTC',
    'Africa/Algiers': 'UTC+1',
    'Africa/Bissau': 'UTC',
    'Africa/Cairo': 'UTC+2',
    'Africa/Casablanca': 'UTC',
    'Africa/Ceuta': 'UTC+1',
    'Africa/El_Aaiun': 'UTC',
    'Africa/Johannesburg': 'UTC+2',
    'Africa/Juba': 'UTC+2',
    'Africa/Khartoum': 'UTC+2',
    'Africa/Lagos': 'UTC+1',
    'Africa/Maputo': 'UTC+2',
    'Africa/Monrovia': 'UTC',
    'Africa/Nairobi': 'UTC+3',
    'Africa/Ndjamena': 'UTC+1',
    'Africa/Sao_Tome': 'UTC',
    'Africa/Tripoli': 'UTC+2',
    'Africa/Tunis': 'UTC+1',
    'Africa/Windhoek': 'UTC+2',
    'America/Anchorage': 'UTC-9',
    'America/Araguaina': 'UTC-3',
    'America/Argentina/Buenos_Aires': 'UTC-3',
    'America/Argentina/Catamarca': 'UTC-3',
    'America/Asuncion': 'UTC-4',
    'America/Bahia': 'UTC-3',
    'America/Bahia_Banderas': 'UTC-6',
    'America/Barbados': 'UTC-4',
    'America/Belem': 'UTC-3',
    'America/Belize': 'UTC-6',
    'America/Boa_Vista': 'UTC-4',
    'America/Bogota': 'UTC-5',
    'America/Boise': 'UTC-7',
    'America/Cambridge_Bay': 'UTC-7',
    'America/Campo_Grande': 'UTC-4',
    'America/Cancun': 'UTC-5',
    'America/Caracas': 'UTC-4',
    'America/Cayenne': 'UTC-3',
    'America/Chicago': 'UTC-6',
    'America/Chihuahua': 'UTC-6',
    'America/Ciudad_Juarez': 'UTC-7',
    'America/Costa_Rica': 'UTC-6',
    'America/Cuiaba': 'UTC-4',
    'America/Danmarkshavn': 'UTC',
    'America/Dawson': 'UTC-7',
    'America/Dawson_Creek': 'UTC-7',
    'America/Denver': 'UTC-7',
    'America/Detroit': 'UTC-5',
    'America/Edmonton': 'UTC-7',
    'America/Eirunepe': 'UTC-5',
    'America/El_Salvador': 'UTC-6',
    'America/Fort_Nelson': 'UTC-7',
    'America/Fortaleza': 'UTC-3',
    'America/Glace_Bay': 'UTC-4',
    'America/Goose_Bay': 'UTC-4',
    'America/Grand_Turk': 'UTC-5',
    'America/Guatemala': 'UTC-6',
    'America/Guayaquil': 'UTC-5',
    'America/Guyana': 'UTC-4',
    'America/Halifax': 'UTC-4',
    'America/Havana': 'UTC-5',
    'America/Hermosillo': 'UTC-7',
    'America/Indiana/Indianapolis': 'UTC-5',
    'America/Indiana/Knox': 'UTC-6',
    'America/Indiana/Marengo': 'UTC-5',
    'America/Indiana/Petersburg': 'UTC-5',
    'America/Indiana/Tell_City': 'UTC-6',
    'America/Indiana/Vevay': 'UTC-5',
    'America/Indiana/Vincennes': 'UTC-5',
    'America/Indiana/Winamac': 'UTC-5',
    'America/Inuvik': 'UTC-7',
    'America/Iqaluit': 'UTC-5',
    'America/Juneau': 'UTC-9',
    'America/Kentucky/Louisville': 'UTC-5',
    'America/Kentucky/Monticello': 'UTC-5',
    'America/La_Paz': 'UTC-4',
    'America/Lima': 'UTC-5',
    'America/Los_Angeles': 'UTC-8',
    'America/Maceio': 'UTC-3',
    'America/Managua': 'UTC-6',
    'America/Manaus': 'UTC-4',
    'America/Martinique': 'UTC-4',
    'America/Matamoros': 'UTC-6',
    'America/Mazatlan': 'UTC-7',
    'America/Menominee': 'UTC-6',
    'America/Merida': 'UTC-6',
    'America/Metlakatla': 'UTC-9',
    'America/Mexico_City': 'UTC-6',
    'America/Miquelon': 'UTC-3',
    'America/Moncton': 'UTC-4',
    'America/Monterrey': 'UTC-6',
    'America/Montevideo': 'UTC-3',
    'America/New_York': 'UTC-5',
    'America/Nome': 'UTC-9',
    'America/Noronha': 'UTC-2',
    'America/North_Dakota/Beulah': 'UTC-6',
    'America/North_Dakota/Center': 'UTC-6',
    'America/North_Dakota/New_Salem': 'UTC-6',
    'America/Nuuk': 'UTC-2',
    'America/Ojinaga': 'UTC-6',
    'America/Panama': 'UTC-5',
    'America/Paramaribo': 'UTC-3',
    'America/Phoenix': 'UTC-7',
    'America/Port-au-Prince': 'UTC-5',
    'America/Porto_Velho': 'UTC-4',
    'America/Puerto_Rico': 'UTC-4',
    'America/Punta_Arenas': 'UTC-3',
    'America/Rankin_Inlet': 'UTC-6',
    'America/Recife': 'UTC-3',
    'America/Regina': 'UTC-6',
    'America/Resolute': 'UTC-6',
    'America/Rio_Branco': 'UTC-5',
    'America/Santarem': 'UTC-3',
    'America/Santiago': 'UTC-4',
    'America/Santo_Domingo': 'UTC-4',
    'America/Sao_Paulo': 'UTC-3',
    'America/Scoresbysund': 'UTC-1',
    'America/Sitka': 'UTC-9',
    'America/St_Johns': 'UTC-3',
    'America/Swift_Current': 'UTC-6',
    'America/Tegucigalpa': 'UTC-6',
    'America/Thule': 'UTC-4',
    'America/Thunder_Bay': 'UTC-5',
    'America/Tijuana': 'UTC-8',
    'America/Toronto': 'UTC-5',
    'America/Vancouver': 'UTC-8',
    'America/Whitehorse': 'UTC-7',
    'America/Winnipeg': 'UTC-6',
    'America/Yakutat': 'UTC-9',
    'Asia/Almaty': 'UTC+5',
    'Asia/Amman': 'UTC+3',
    'Asia/Anadyr': 'UTC+12',
    'Asia/Aqtau': 'UTC+5',
    'Asia/Aqtobe': 'UTC+5',
    'Asia/Ashgabat': 'UTC+5',
    'Asia/Atyrau': 'UTC+5',
    'Asia/Baghdad': 'UTC+3',
    'Asia/Baku': 'UTC+4',
    'Asia/Bangkok': 'UTC+7',
    'Asia/Barnaul': 'UTC+7',
    'Asia/Beirut': 'UTC+2',
    'Asia/Bishkek': 'UTC+6',
    'Asia/Brunei': 'UTC+8',
    'Asia/Chita': 'UTC+9',
    'Asia/Choibalsan': 'UTC+8',
    'Asia/Colombo': 'UTC+5',
    'Asia/Damascus': 'UTC+3',
    'Asia/Dhaka': 'UTC+6',
    'Asia/Dili': 'UTC+9',
    'Asia/Dubai': 'UTC+4',
    'Asia/Dushanbe': 'UTC+5',
    'Asia/Famagusta': 'UTC+2',
    'Asia/Gaza': 'UTC+2',
    'Asia/Hebron': 'UTC+2',
    'Asia/Ho_Chi_Minh': 'UTC+7',
    'Asia/Hong_Kong': 'UTC+8',
    'Asia/Hovd': 'UTC+7',
    'Asia/Irkutsk': 'UTC+8',
    'Asia/Jakarta': 'UTC+7',
    'Asia/Jayapura': 'UTC+9',
    'Asia/Jerusalem': 'UTC+2',
    'Asia/Kabul': 'UTC+4',
    'Asia/Kamchatka': 'UTC+12',
    'Asia/Karachi': 'UTC+5',
    'Asia/Kathmandu': 'UTC+5',
    'Asia/Khandyga': 'UTC+9',
    'Asia/Kolkata': 'UTC+5',
    'Asia/Krasnoyarsk': 'UTC+7',
    'Asia/Kuala_Lumpur': 'UTC+8',
    'Asia/Kuching': 'UTC+8',
    'Asia/Macau': 'UTC+8',
    'Asia/Magadan': 'UTC+11',
    'Asia/Makassar': 'UTC+8',
    'Asia/Manila': 'UTC+8',
    'Asia/Nicosia': 'UTC+2',
    'Asia/Novokuznetsk': 'UTC+7',
    'Asia/Novosibirsk': 'UTC+7',
    'Asia/Omsk': 'UTC+6',
    'Asia/Oral': 'UTC+5',
    'Asia/Pontianak': 'UTC+7',
    'Asia/Pyongyang': 'UTC+9',
    'Asia/Qatar': 'UTC+3',
    'Asia/Qostanay': 'UTC+5',
    'Asia/Qyzylorda': 'UTC+5',
    'Asia/Riyadh': 'UTC+3',
    'Asia/Sakhalin': 'UTC+11',
    'Asia/Samarkand': 'UTC+5',
    'Asia/Seoul': 'UTC+9',
    'Asia/Shanghai': 'UTC+8',
    'Asia/Singapore': 'UTC+8',
    'Asia/Srednekolymsk': 'UTC+11',
    'Asia/Taipei': 'UTC+8',
    'Asia/Tashkent': 'UTC+5',
    'Asia/Tbilisi': 'UTC+4',
    'Asia/Tehran': 'UTC+3',
    'Asia/Thimphu': 'UTC+6',
    'Asia/Tokyo': 'UTC+9',
    'Asia/Tomsk': 'UTC+7',
    'Asia/Ulaanbaatar': 'UTC+8',
    'Asia/Urumqi': 'UTC+6',
    'Asia/Ust-Nera': 'UTC+10',
    'Asia/Vientiane': 'UTC+7',
    'Asia/Vladivostok': 'UTC+10',
    'Asia/Yakutsk': 'UTC+9',
    'Asia/Yangon': 'UTC+6',
    'Asia/Yekaterinburg': 'UTC+5',
    'Asia/Yerevan': 'UTC+4',
    'Atlantic/Azores': 'UTC-1',
    'Atlantic/Bermuda': 'UTC-4',
    'Atlantic/Canary': 'UTC',
    'Atlantic/Cape_Verde': 'UTC-1',
    'Atlantic/Faroe': 'UTC',
    'Atlantic/Madeira': 'UTC',
    'Atlantic/Reykjavik': 'UTC',
    'Atlantic/South_Georgia': 'UTC-2',
    'Atlantic/Stanley': 'UTC-3',
    'Australia/Adelaide': 'UTC+9',
    'Australia/Brisbane': 'UTC+10',
    'Australia/Broken_Hill': 'UTC+9',
    'Australia/Darwin': 'UTC+9',
    'Australia/Eucla': 'UTC+8',
    'Australia/Hobart': 'UTC+10',
    'Australia/Lindeman': 'UTC+10',
    'Australia/Lord_Howe': 'UTC+10',
    'Australia/Melbourne': 'UTC+10',
    'Australia/Perth': 'UTC+8',
    'Australia/Sydney': 'UTC+10',
    'Europe/Amsterdam': 'UTC+1',
    'Europe/Andorra': 'UTC+1',
    'Europe/Astrakhan': 'UTC+4',
    'Europe/Athens': 'UTC+2',
    'Europe/Belgrade': 'UTC+1',
    'Europe/Berlin': 'UTC+1',
    'Europe/Brussels': 'UTC+1',
    'Europe/Bucharest': 'UTC+2',
    'Europe/Budapest': 'UTC+1',
    'Europe/Chisinau': 'UTC+2',
    'Europe/Copenhagen': 'UTC+1',
    'Europe/Dublin': 'UTC',
    'Europe/Gibraltar': 'UTC+1',
    'Europe/Helsinki': 'UTC+2',
    'Europe/Istanbul': 'UTC+3',
    'Europe/Kaliningrad': 'UTC+2',
    'Europe/Kirov': 'UTC+3',
    'Europe/Kyiv': 'UTC+2',
    'Europe/Lisbon': 'UTC',
    'Europe/Ljubljana': 'UTC+1',
    'Europe/London': 'UTC',
    'Europe/Luxembourg': 'UTC+1',
    'Europe/Madrid': 'UTC+1',
    'Europe/Malta': 'UTC+1',
    'Europe/Minsk': 'UTC+3',
    'Europe/Monaco': 'UTC+1',
    'Europe/Moscow': 'UTC+3',
    'Europe/Oslo': 'UTC+1',
    'Europe/Paris': 'UTC+1',
    'Europe/Prague': 'UTC+1',
    'Europe/Riga': 'UTC+2',
    'Europe/Rome': 'UTC+1',
    'Europe/Samara': 'UTC+4',
    'Europe/Saratov': 'UTC+4',
    'Europe/Simferopol': 'UTC+3',
    'Europe/Sofia': 'UTC+2',
    'Europe/Stockholm': 'UTC+1',
    'Europe/Tallinn': 'UTC+2',
    'Europe/Tirane': 'UTC+1',
    'Europe/Ulyanovsk': 'UTC+4',
    'Europe/Vienna': 'UTC+1',
    'Europe/Vilnius': 'UTC+2',
    'Europe/Volgograd': 'UTC+3',
    'Europe/Warsaw': 'UTC+1',
    'Europe/Zurich': 'UTC+1',
    'Indian/Chagos': 'UTC+6',
    'Indian/Christmas': 'UTC+7',
    'Indian/Cocos': 'UTC+6',
    'Indian/Kerguelen': 'UTC+5',
    'Indian/Mahe': 'UTC+4',
    'Indian/Maldives': 'UTC+5',
    'Indian/Mauritius': 'UTC+4',
    'Indian/Reunion': 'UTC+4',
    'Pacific/Apia': 'UTC+13',
    'Pacific/Auckland': 'UTC+12',
    'Pacific/Bougainville': 'UTC+11',
    'Pacific/Chatham': 'UTC+12',
    'Pacific/Easter': 'UTC-6',
    'Pacific/Efate': 'UTC+11',
    'Pacific/Fakaofo': 'UTC+13',
    'Pacific/Fiji': 'UTC+12',
    'Pacific/Funafuti': 'UTC+12',
    'Pacific/Galapagos': 'UTC-6',
    'Pacific/Gambier': 'UTC-9',
    'Pacific/Guadalcanal': 'UTC+11',
    'Pacific/Guam': 'UTC+10',
    'Pacific/Honolulu': 'UTC-10',
    'Pacific/Kanton': 'UTC+13',
    'Pacific/Kiritimati': 'UTC+14',
    'Pacific/Kosrae': 'UTC+11',
    'Pacific/Kwajalein': 'UTC+12',
    'Pacific/Majuro': 'UTC+12',
    'Pacific/Marquesas': 'UTC-9',
    'Pacific/Nauru': 'UTC+12',
    'Pacific/Niue': 'UTC-11',
    'Pacific/Norfolk': 'UTC+11',
    'Pacific/Noumea': 'UTC+11',
    'Pacific/Pago_Pago': 'UTC-11',
    'Pacific/Palau': 'UTC+9',
    'Pacific/Pitcairn': 'UTC-8',
    'Pacific/Port_Moresby': 'UTC+10',
    'Pacific/Rarotonga': 'UTC-10',
    'Pacific/Tahiti': 'UTC-10',
    'Pacific/Tarawa': 'UTC+12',
    'Pacific/Tongatapu': 'UTC+13',
    'Pacific/Wake': 'UTC+12',
    'Pacific/Wallis': 'UTC+12',
    'Antarctica/Casey': 'UTC+8',
    'Antarctica/Davis': 'UTC+7',
    'Antarctica/Macquarie': 'UTC+10',
    'Antarctica/Mawson': 'UTC+5',
    'Antarctica/Troll': 'UTC',
    'Antarctica/Vostok': 'UTC+5',
    'Arctic/Longyearbyen': 'UTC+1',
    'Etc/GMT': 'UTC',
    'Etc/GMT+1': 'UTC-1',
    'Etc/GMT+2': 'UTC-2',
    'Etc/GMT+3': 'UTC-3',
    'Etc/GMT+4': 'UTC-4',
    'Etc/GMT+5': 'UTC-5',
    'Etc/GMT+6': 'UTC-6',
    'Etc/GMT+7': 'UTC-7',
    'Etc/GMT+8': 'UTC-8',
    'Etc/GMT+9': 'UTC-9',
    'Etc/GMT+10': 'UTC-10',
    'Etc/GMT+11': 'UTC-11',
    'Etc/GMT+12': 'UTC-12',
    'Etc/GMT-1': 'UTC+1',
    'Etc/GMT-2': 'UTC+2',
    'Etc/GMT-3': 'UTC+3',
    'Etc/GMT-4': 'UTC+4',
    'Etc/GMT-5': 'UTC+5',
    'Etc/GMT-6': 'UTC+6',
    'Etc/GMT-7': 'UTC+7',
    'Etc/GMT-8': 'UTC+8',
    'Etc/GMT-9': 'UTC+9',
    'Etc/GMT-10': 'UTC+10',
    'Etc/GMT-11': 'UTC+11',
    'Etc/GMT-12': 'UTC+12',
    'Etc/GMT-13': 'UTC+13',
    'Etc/GMT-14': 'UTC+14',
    'Etc/UTC': 'UTC',
};

const VALID_UTC_OFFSETS = new Set([
    'browser', 'UTC',
    'UTC+1', 'UTC+2', 'UTC+3', 'UTC+4', 'UTC+5', 'UTC+6',
    'UTC+7', 'UTC+8', 'UTC+9', 'UTC+10', 'UTC+11', 'UTC+12',
    'UTC-1', 'UTC-2', 'UTC-3', 'UTC-4', 'UTC-5', 'UTC-6',
    'UTC-7', 'UTC-8', 'UTC-9', 'UTC-10', 'UTC-11', 'UTC-12',
]);

export function migrate_iana_timezone(value: string): string {
    if (VALID_UTC_OFFSETS.has(value)) return value;
    const mapped = IANA_TO_OFFSET[value];
    if (mapped && VALID_UTC_OFFSETS.has(mapped)) return mapped;
    return 'browser';
}

export async function load_user_config(): Promise<UserConfig> {
    try {
        const result = await chrome.storage.local.get(STORAGE_KEY);
        const stored = result[STORAGE_KEY] as Partial<UserConfig> | undefined;
        const merged = { ...DEFAULT_USER_CONFIG, ...(stored || {}) };

        // P0.34: migrate old IANA timezone values to fixed UTC offsets
        if (merged.system_time_timezone) {
            const migrated = migrate_iana_timezone(merged.system_time_timezone);
            if (migrated !== merged.system_time_timezone) {
                merged.system_time_timezone = migrated as SystemTimeTimezone;
                // Persist the migration immediately
                try {
                    await chrome.storage.local.set({ [STORAGE_KEY]: merged });
                } catch {
                    // Best-effort migration; if persistence fails, the in-memory
                    // value is still correct for this session
                }
            }
        }

        return merged as UserConfig;
    } catch {
        return { ...DEFAULT_USER_CONFIG } as UserConfig;
    }
}

export async function save_user_config(patch: Partial<UserConfig>): Promise<void> {
    const current = await load_user_config();
    const next: UserConfig = { ...current, ...patch };
    await chrome.storage.local.set({ [STORAGE_KEY]: next });
}
