// background/exporter.ts
import { escape_for_html_embed } from '../shared/escape';
import { get_session, get_events, get_network_requests, get_console_logs } from './storage';

export async function export_json(session_id: string): Promise<string> {
    const session = await get_session(session_id);
    if (!session) throw new Error('Session not found');

    const [events, network_requests, console_logs] = await Promise.all([
        get_events(session_id, 0, 100000),
        get_network_requests(session_id, 0, 100000),
        get_console_logs(session_id, 0, 100000)
    ]);

    const data = { session, events, network_requests, console_logs };
    return JSON.stringify(data, null, 2);
}

export async function export_html(session_id: string): Promise<string> {
    const session = await get_session(session_id);
    if (!session) throw new Error('Session not found');

    const [events, network_requests, console_logs] = await Promise.all([
        get_events(session_id, 0, 100000),
        get_network_requests(session_id, 0, 100000),
        get_console_logs(session_id, 0, 100000)
    ]);

    const data = { session, events, network_requests, console_logs };
    const json_str = JSON.stringify(data);
    const safe_json = escape_for_html_embed(json_str);

    const start_date = new Date(session.start_time).toISOString();
    const duration_ms = session.end_time ? session.end_time - session.start_time : 0;
    const duration_str = format_duration(duration_ms);

    const total_size_kb = Math.round(
        (session.stats.event_count + session.stats.request_count + session.stats.log_count) * 0.5
    );

    return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Record All - Session ${session_id}</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; color: #333; }
.container { max-width: 960px; margin: 0 auto; }
h1 { font-size: 20px; margin-bottom: 8px; }
.summary { background: white; border-radius: 8px; padding: 16px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
.summary-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 12px; }
.summary-item label { font-size: 11px; color: #666; display: block; }
.summary-item span { font-weight: 500; font-size: 14px; }
details { background: white; border-radius: 8px; padding: 16px; margin-bottom: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
summary { cursor: pointer; font-weight: 500; }
pre { background: #f8f8f8; padding: 12px; border-radius: 4px; overflow-x: auto; font-size: 12px; max-height: 500px; overflow-y: auto; }
.footer { text-align: center; padding: 16px; color: #999; font-size: 11px; }
</style>
</head>
<body>
<div class="container">
<h1>Record All - Session Report</h1>
<div class="summary">
  <div class="summary-grid">
    <div class="summary-item"><label>Session ID</label><span>${session_id}</span></div>
    <div class="summary-item"><label>Start Time</label><span>${start_date}</span></div>
    <div class="summary-item"><label>Duration</label><span>${duration_str}</span></div>
    <div class="summary-item"><label>Mode</label><span>${session.config.capture_mode}</span></div>
    <div class="summary-item"><label>Events</label><span>${session.stats.event_count}</span></div>
    <div class="summary-item"><label>Network Requests</label><span>${session.stats.request_count}</span></div>
    <div class="summary-item"><label>Console Logs</label><span>${session.stats.log_count}</span></div>
    <div class="summary-item"><label>Est. Size</label><span>${total_size_kb} KB</span></div>
  </div>
</div>

<details>
  <summary>View Raw Data (JSON)</summary>
  <pre id="jsonData"></pre>
</details>

<div class="footer">Generated by Record All</div>
</div>
<script>
const data = JSON.parse('${safe_json}');
document.getElementById('jsonData').textContent = JSON.stringify(data, null, 2);
</script>
</body>
</html>`;
}

function format_duration(ms: number): string {
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    const hours = Math.floor(minutes / 60);
    if (hours > 0) return hours + 'h ' + (minutes % 60) + 'm ' + (seconds % 60) + 's';
    return minutes + 'm ' + (seconds % 60) + 's';
}
